# Generated by Django 4.2.30 on 2026-04-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(blank=True, max_length=300)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                ("reviews_count", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("book_url", models.URLField(max_length=1000, unique=True)),
                ("cover_image_url", models.URLField(blank=True, max_length=1000)),
                ("genre", models.CharField(blank=True, max_length=200)),
                ("price", models.CharField(blank=True, max_length=50)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-scraped_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("sources", models.JSONField(default=list)),
                ("asked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("genre_predicted", models.CharField(blank=True, max_length=200)),
                ("sentiment", models.CharField(blank=True, max_length=50)),
                ("sentiment_score", models.FloatField(null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight",
                        to="books.book",
                    ),
                ),
            ],
        ),
    ]
